### ISSUE TITLE
Freesurfer 6.0.0-min missing files for recon-all -all

### ISSUE THREAD

**Issue by frandorr** [ReproNim/neurodocker#285]
The default Freesurfer 6.0.0-min fails when running `recon-all -all` command (at least when `-parallel` and `-openmp` flags are on) . 
There are two missing files: `reconbatchjobs` and `mri_seg_diff` 
I added those binaries and it worked great.

Thank you

**Comment by kaczmarj** [comment]
hi @frandorr - the minimized version of freesurfer's `recon-all` was created according to https://github.com/freesurfer/freesurfer/issues/70. i guess `mri_seg_diff` and `reconbatchjobs` were not caught during those runs in the linked issue. i can potentially add those two files to the minimized tarball so that `recon-all -all` works.

**Comment by frandorr** [comment]
Thank you for your answer @kaczmarj. I created a docker image with those files and uploaded it to docker hub. Here you can find it: https://hub.docker.com/r/entelai/freesurfer-min.
Your are doing an amazing job with neurodocker!

**Comment by djarecka** [comment]
if this issue still persists in the newer version please reopen.
