### ISSUE TITLE
NeuroDocker install new packages inside the image

### ISSUE THREAD

**Issue by kaurbhupinder** [ReproNim/neurodocker#307]
I managed to minimize Docker image (bids/example) with Neurodocker but I noticed that one new package(curl) is installed inside the minimized image. Why this package is installed because I was expecting Neurodocker will reduce number of packages installed inside the image by removing unnecessary packages.

**Comment by kaczmarj** [comment]
hi @kaurbhupinder - can you please give more information about the problem? can you share the commands you used to minimize the `bids/example` image?

**Comment by kaurbhupinder** [comment]
@kaczmarj I followed the steps given in issue  #295 and link is below https://github.com/kaczmarj/neurodocker/issues/295

**Comment by kaczmarj** [comment]
the method in #295 is a "gentle" way of minimizing an image. it only cleans things out of certain directories, like `/opt`. programs like `curl` are installed by `apt-get` and live under `/usr`. i made this gentle minimization method in #258 because doing a full minimization (i.e., deleting everything except files caught by the trace) often creates containers that can no longer be used interactively. they can only be used for the commands used during minimization. if you want to prune more than just `/opt`, you can add more directories to the `ndminify` call.

if you want to do a full minimization, can you try https://github.com/kaczmarj/neurodocker#minimize-existing-docker-image ?

**Comment by kaurbhupinder** [comment]
@kaczmarj thanks for the explanation and I do understand that. I have two doubts:
1. Do Neurodocker deletes unnecessary packages that are present inside the image?
2. For bids/example I checked for original image there is no curl package inside the image. However 
when I minimised it and noticed that curl package is installed. Any explanation will be much appreciated. Thanks

**Comment by sooyounga** [comment]
hi we're trying to clean up our issues and decided to close this issue, please reopen if necessary
