### ISSUE TITLE
[DOC] missing commands in the online doc

### ISSUE THREAD

**Issue by Remi-Gau** [ReproNim/neurodocker#461]
Not urgent but I think that some commands are not listed in the online doc.

For some reason I tend to go for the online doc rather that typing `--help` and I got confused by some things I knew should be there.

Comparing for example:
- https://www.repronim.org/neurodocker/user_guide/cli.html#neurodocker-generate-docker

With:
docker run -it --rm repronim/neurodocker:0.7.0 generate docker --help

Missing things like 
- `--entrypoint`
- `--cmd`

**Comment by kaczmarj** [comment]
thanks @Remi-Gau for pointing this out - the docs definitely need work. good to know that you are using the online doc rather than `--help` -- i'm sure many others do the same. given that, docs need to become a priority.

thanks for the missing items. to anyone reading this, pull requests are welcome of course. i'll try to address this issue in the coming days if no pull requests come in.

**Comment by Remi-Gau** [comment]
I have not had a close look but I think that most of your doc must be auto generated through some sphinx / rst directives.

Not sure where the discrepancy is coming from. If that part of the doc is generated manually, then that is probably what needs to change. :-)

**Comment by satra** [comment]
we may want to enable the click doc extension that we use in dandi cli: https://dandi.readthedocs.io/en/latest/

**Comment by kaczmarj** [comment]
@satra - thanks for the pointer. had not seen that before.
