### ISSUE TITLE
neurodocker works with M1 apple?

### ISSUE THREAD

**Issue by yyang1234** [ReproNim/neurodocker#477]
seems that I get this warning on my M1 apple

what I tried:

```
docker run --rm repronim/neurodocker:latest generate docker \
	--base debian:stretch-slim \
	--pkg-manager apt \
        ...
```

warning:

```
The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

the generation of the dockerfile never happens

**Comment by kaczmarj** [comment]
@yyang1234 - i don't have an M1 mac so can't try myself, but can you run this? (from https://stackoverflow.com/a/68004485/5666087)

```
docker run --platform linux/amd64 --rm repronim/neurodocker:latest generate docker \
	--base debian:stretch-slim \
	--pkg-manager apt \
        ...
```

note addition of `--platform linux/amd64`

**Comment by djarecka** [comment]
Just want to comment that I do have M1 and for me I can run `docker run --rm repronim/neurodocker:latest generate docker` to produce a Dockerfile, I just have the warnings, but the Dockerflie is created.

However, in order to build an image that work for linux/amd64, I have to use `--platform linux/amd64` with the `docker build` command

**Comment by djarecka** [comment]
I believe this has been solved, but please feel free to reopen if needed
