### ISSUE TITLE
Relaxing click dependency to work with >v8.0

### ISSUE THREAD

**Issue by tclose** [ReproNim/neurodocker#479]
Hi @kaczmarj,

Do you know what would be involved with relaxing the restriction on click<8.0? It is causing dependency conflicts for me and it would be great to be able to resolve it. I might have some time in Dec or Jan to have a look at it if it isn't too big of a fix.

Cheers,

Tom

**Comment by kaczmarj** [comment]
@tclose - that would be great. i introduced the <8.0 restriction in https://github.com/ReproNim/neurodocker/pull/401/commits/50b22f8c73ef864dd2dffd8876f7add2cbb15330 . here is the commit message:

>Click version 8.0 seems to break our CLI... for example, the multi
option --install returns a string with click 8. Before, it would return
a tuple. I do not know why it would be returning a string...

and i confirmed now with click 8.1.3 that this still happens. 

the problem seems to be in https://github.com/ReproNim/neurodocker/blob/ad2f3a62afa9a8852bbf0ff3f1df1aadb3b74c8d/neurodocker/cli/generate.py#L140-L143

**Comment by tclose** [comment]
I believe this issue has been resolved now
