### ISSUE TITLE
renderer schema error

### ISSUE THREAD

**Issue by satra** [ReproNim/neurodocker#491]
this command:

```
neurodocker generate docker --json --base-image debian:buster-slim --pkg-manager apt --install git
```

fails with a schema error:

```
jsonschema.exceptions.ValidationError: {'name': 'install', 'kwds': {'pkgs': "('git',)", 'opts': None}} is not valid under any of the given schemas
```

and that's because the `pkgs` schema is expecting a list and getting a string of tuple.

**Comment by kaczmarj** [comment]
My first thought is that this is an issue with the click parameter subclass that ingests an arbitrary number of arguments. Click does not natively have a mechanism like argparse nargs=“+”On Jan 14, 2023, at 12:52, Satrajit Ghosh ***@***.***> wrote:﻿
this command:
neurodocker generate docker --json --base-image debian:buster-slim --pkg-manager apt --install git

fails with a schema error:
jsonschema.exceptions.ValidationError: {'name': 'install', 'kwds': {'pkgs': "('git',)", 'opts': None}} is not valid under any of the given schemas

and that's because the pkgs schema is expecting a list and getting a string of tuple.

**Comment by satra** [comment]
yup - that's the section i'm trying to figure out.
